apiVersion: apps/v1
kind: Deployment
metadata:
  name: foodhub-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foodhub-app
  template:
    metadata:
      labels:
        app: foodhub-app
    spec:
      containers:
      - name: foodhub-container
        image: shreyasc19/foodhub-image:latest
        ports:
        - containerPort: 80