apiVersion: v1
kind: Service
metadata:
  name: foodhub-service
  annotations:
    logging: "true"
spec:
  selector:
    app: foodhub-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32000
